### ISSUE TITLE
can't find exp1.yml

### ISSUE THREAD

**Issue by liudi-didi** [thomeou/General-network-architecture-for-sound-event-localization-and-detection#1]
Hello,I can't find the configuration file exp1.yml.What's in this file?This error was reported ''DummyClass' object has no attribute 'feature_dir''.Thanks a million!!!!
The following error occurs of running train.py 

Traceback (most recent call last):
  File "F:/Desktop/seldddd/experiments/train.py", line 86, in <module>
    fire.Fire(train)
  File "F:\Desktop\torch_even\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "F:\Desktop\torch_even\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "F:\Desktop\torch_even\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "F:/Desktop/seldddd/experiments/train.py", line 30, in train
    cfg = manage_experiments(exp_config=exp_config, exp_group_dir=exp_group_dir, exp_suffix=exp_suffix, empty=empty)
  File "F:\Desktop\seldddd\utilities\experiments_utils.py", line 40, in manage_experiments
    cfg.feature_type = os.path.split(os.path.split(cfg.feature_dir)[0])[-1]
AttributeError: 'DummyClass' object has no attribute 'feature_dir'

**Comment by thomeou** [comment]
Hi, 

I am sorry for the incomplete code uploaded here. I have released a new repository that achieved better SELD performance than this repo. If you are still keen on working on SELD problem, please use the other repo instead. I posted the link here: https://github.com/thomeou/SALSA
